config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', shared: 'users/shared'}

  devise_scope :user do
    authenticated :user do
      root 'labo#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    get '/users/sign_out' => 'users/sessions#destroy', as: "destroy_session"
    get '/users/delete' => 'users/registrations#destroy', as: "destroy_registration"
    get 'users/labo' => 'users/registrations#retrieve_labo', as: 'retrieve_labo'
    post 'users/labo' => 'users/registrations#find_labo', as: "find_labo"
  end

  resources :protocols, only: [:index, :show, :new, :create, :destroy] do
    resources :procedures, only: [:create]
  end
  resources :custom_protocols, only: [ :new]


  #ログイン＆新規登録画面
    get  'thanks' => 'thanks#index'

     #管理画面トップ
    get  'admin' => 'admin#index'


   #研究室新規登録ページ&研究室ページ
    get  'labo' => 'labo#index'
    get  'labo/show/:id' => 'labo#show', as: "labo_show"
    get  'labo/new' => 'labo#new', as: "new_affiliation"
    post 'labo/new' => 'labo#create', as: "affiliations"

   #研究室パスワード移行ページ
    get  'labo_pass/:id' => 'labo_pass#index', as: "labo_pass"

  #実験結果ページ
    get  'experiment' => 'experiment#index'
    get  'experiment/show/:id' => 'experiment#show', as: "experiment_show"
    get  'experiment/new' => 'experiment#new', as: "new_experiment"
    post 'experiment/new' => 'experiment#create', as: "experiments"

  #コメント
    post 'experiment/show/:id' => 'experiment#comment_create', as: "comments"

  #研究室所属一覧


  get 'pages/show'
    get  'login' => 'login#index'
    get  'login/new'  =>  'login#new'
    get  'user' => 'user#index'
    get  'user/show/:id' => 'user#show', as: "user_show"

  #スタンダード(テンプレート)プロトコル一覧
    get  'standard' => 'standard#index'
    get  'standard/show/:id' => 'standard#show', as: "standard_show"
    get  'standard/new' => 'standard#new'

  #ベースプロトコル一覧
    get  'base' => 'base#index'
    get  'base/show/:id' => 'base#show', as: "base_show"
    get  'base/new' => 'base#new'

  #カスタムプロトコル一覧
    get  'custom' => 'custom#index'
    get  'custom/show/:id' => 'custom#show', as: "custom_show"
    get  'custom/new' => 'custom#new'


    get  'search' => 'search#index'


  end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    validates :university,  presence: true
    validates :department, presence: true
    validates :course,  presence: true
    validates :labo, presence: true
    validates :cord, presence: true, length: { minimum: 8 }
    has_many :users
    has_many :protocols
    has_many :experiments
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category_name, presence: true
    has_many :experiments
    has_many :protocols
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :experiment
    validates :comment, presence: true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
    acts_as_taggable
    belongs_to :user
    belongs_to :protocol 
    belongs_to :category
    belongs_to :affiliation
    has_many :comments, dependent: :destroy
    attr_accessor :new_category
      
    validates :title, presence: true, length: { maximum: 20 } #仮で２０とした。不要かも
    validates :date, presence: true
    validates :overview, presence: true
    validates :result, presence: true
    validates :user_id, presence: true
    
    mount_uploader :image, ImageUploader
    
    #検索機能
    def self.search(keyword, user)
        return Experiment.where("affiliation_id = ?", user.affiliation_id) unless keyword
        Experiment.where('title LIKE ? AND affiliation_id = ?', "%#{keyword}%", user.affiliation_id).distinct
    end
    
    def self.search_admin(keyword)
        return Experiment.all unless keyword
        Experiment.where('title LIKE ?', "%#{keyword}%").distinct
    end
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :protocol

  validates :text, presence: true
  validates :position, presence: true
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  belongs_to :user
  belongs_to :affiliation
  belongs_to :category
  has_many :procedures, inverse_of: :protocol, dependent: :destroy
  has_many :experiments
  has_many :comments

  attr_accessor :new_category

  acts_as_taggable

  accepts_nested_attributes_for :procedures, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :status, presence: true
  validates :parent_id, presence: true

  enum status: {base: 0, custom: 1, template: 2}

  # Constant for enum
  BASE = 0
  CUSTOM = 1
  TEMPLATE =2

  # add position to procedures
  after_save do |protocol|
    procedures = Procedure.where(protocol_id: protocol.id)
    add_position = 0
    procedures.each do |procedure|
      add_position += 1
      procedure.position = add_position
      procedure.save!
    end
  end
  
  #検索機能
  def self.search(keyword, num, user)
    return Protocol.where("status =? AND affiliation_id = ?", num, user.affiliation_id) unless keyword
    Protocol.where("status = ? AND affiliation_id = ? AND title LIKE ?", num, user.affiliation_id, "%#{keyword}%").distinct
  end
  
  def self.search_admin(keyword, num)
    return Protocol.where(status: num) unless keyword
    Protocol.where("status = ? AND title LIKE ?", num, "%#{keyword}%").distinct
  end
end

app/models/user.rb
class User < ApplicationRecord
  #include ActiveModel::Model
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

  belongs_to :affiliation
  has_many :experiments
  has_many :comments
  has_many :protocols

  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :avatar, AvatarUploader


end

app/controllers/standard_controller.rb
class StandardController < ApplicationController
  before_action :authenticate_user!
  def index
    @protocols = Protocol.where(status: Protocol::TEMPLATE).page(params[:page]).per(10)
  end

  def new
    current_user_is_admin
    @protocol = Protocol.new(status: Protocol::TEMPLATE)
    @protocol.procedures.build
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/custom_helper.rb
module CustomHelper
end

app/helpers/experiment_helper.rb
module ExperimentHelper
end

app/helpers/labo_helper.rb
module LaboHelper
    require 'securerandom'
end

app/helpers/labo_pass_helper.rb
module LaboPassHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
  def kind_of_protocol(status)
    if status == "template"
      return "テンプレートプロトコル"
    elsif status == "base"
      return "ベースプロトコル"
    elsif status == "custom"
      return "カスタムプロトコル"
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # 渡されたユーザーをログイン
  def log_in(user)
    session[:user_id] = user.id
  end

  # 永続セッションとしてユーザーを記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークン (cookie) に対応するユーザーを返す
  def current_user
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/standard_helper.rb
module StandardHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(user)
    first_name = user.first_name
    last_name = user.last_name
    user_name = first_name + last_name
    return user_name
  end
end

app/views/standard/_procedure_fields.html.erb
<div class="nested-fields row mb-3">
  <div class="col-md-7" style="background: rgba(255, 252, 252, 0.56); padding: 20px;">
    <%= f.text_area :text, rows: 4, class: "form-control" %>
  </div>
  <div class="col-md-3 mt-md-0 rounded-right" style="background: rgba(255, 252, 252, 0.56); padding: 20px;">
    <%= link_to_remove_association "手順を削除", f, class: "btn btn-outline-danger" %>
  </div>
</div>

app/views/standard/index.html.erb
<nav>

<%= render partial: "render/nav1" %>

</nav>

<main class="CustomList-screen wf-roundedmplus1c">
  <article>
    <section id="BGP-researchable">
      <div class="BGP-Opacity1" style="padding-top: 100px;">
      <div class="container">        <!-- 全体を囲むコンテナ -->
  <h2 class="my-5"><img src="/assets/Admin/result.png" style="margin-right: 10px;">テンプレートプロトコル</h2>

  <div class="d-sm-flex flex-wrap text-black">
    <%= @protocols.each do |protocol| %>
      <div class="bg-info p-3 mb-2 mr-sm-2 Custom-Box">
        <%= link_to protocol_path(id: protocol.id), class: "A-Tag" do %>
          <div class="A-TagEffect">
            <h5>プロトコル名：<%= protocol.title %></h5>
            <p class="mb-0">作成日時：<%= protocol.created_at.strftime('%Y/%m/%d') %></p>
            <p class="mb-0">作成者名：<%= user_name(protocol.user) %></p>
            <p class="mb-0">カテゴリー名：<%= protocol.category.category_name %></p>
          </div>
        <% end %>
      </div>
    <% end%>
    <%= paginate @protocols %>
  </div>

</div>        <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>

app/views/standard/new.html.erb
<nav>
  <%= render partial: "render/nav1" %>
</nav>


<main class="MakeCustom-screen wf-roundedmplus1c">
  <article>
    <section id="BGP-researchable" style="">
      <div class="BGP-Opacity1" style="padding: 125px 0px 25px;">
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-1"></div>
            <div class="col-10">
              <div class="col-md-8">
                <h1 class="mt-4 mb-5"><img class="icon-blank" src="/assets/Admin/file.png"><strong>テンプレートプロトコル作成</strong></h1>
              </div>
            </div>
        </div>
        <%= form_with model: @protocol, local: true do |f| %>
          <div class="row justify-content-center">
            <div class="col-1"></div>
            <div class="col-10">
                <div class="form-group mb-5">
                  <label class="col-md-8 col-form-label mb-2" for="B_Name">タイトル（テンプレートプロトコルの名称）</label>
                  <div class="col-md-8">
                    <%= f.text_field :title, class: "form-control", id: "B_Name" %>
                  </div>
                </div>
            </div>
          </div>
        <div class="container-fluid">        <!-- 全体を囲むコンテナ -->
          <div class="row justify-content-center">
          <div class="col-1"></div>
            <div class="col-10 mb-5">
              <%= f.fields :procedures do |e|%>
                <label for="receipt" class="mb-3">実際の手順</label>
                  <div class="ele">
                    <%= render 'procedure_fields', f: e %>
                  </div>
                  <div class="ele text-center" style="margin-right: 25%;">
                    <%= link_to_add_association "手順を追加", f, :procedures, class: "btn btn-outline-primary" %>
                  </div>
              <% end %>
          </div>
        </div>
        </div>                <!-- 全体を囲むコンテナ -->
        <div class="container-fluid">
          <div class="row justify-content-center">
            <div class="col-1"></div>
              <div class="col-10">
                <div class="form-group col-md-8 mb-4">
                  <%= f.label :category_id, 'カテゴリーを選択するか、新しいカテゴリー名を入力してください。' %>
                  <div class="choice mb-3">
                    <%= f.collection_select :category_id, Category.all, :id, :category_name, prompt: "選択", class: "custom-select" %>
                  </div>
                  <%= f.text_field :new_category, class: "form-control" %>
                </div>
                <div class="form-group col-md-8 mb-4">
                  <%= f.label :tag_list, "タグ(カンマで区切ってください)", class: "col-md-8 col-form-label mb-2" %>
                  <%= f.text_field :tag_list, class: "form-control" %>
                </div>
            </div>
          </div>
          <div class="register text-center">
            <%= f.hidden_field :status %>
            <%= f.submit "登録する", class: 'btn btn-outline-primary btn-register' %>
            <% end %>
          </div>
        </div>
      </div>                <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>