config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', shared: 'users/shared'}

  devise_scope :user do
    authenticated :user do
      root 'labo#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    get '/users/sign_out' => 'users/sessions#destroy', as: "destroy_session"
    get '/users/delete' => 'users/registrations#destroy', as: "destroy_registration"
    get 'users/labo' => 'users/registrations#retrieve_labo', as: 'retrieve_labo'
    post 'users/labo' => 'users/registrations#find_labo', as: "find_labo"
  end

  resources :protocols, only: [:index, :show, :new, :create, :destroy] do
    resources :procedures, only: [:create]
  end
  resources :custom_protocols, only: [ :new]


  #ログイン＆新規登録画面
    get  'thanks' => 'thanks#index'

     #管理画面トップ
    get  'admin' => 'admin#index'


   #研究室新規登録ページ&研究室ページ
    get  'labo' => 'labo#index'
    get  'labo/show/:id' => 'labo#show', as: "labo_show"
    get  'labo/new' => 'labo#new', as: "new_affiliation"
    post 'labo/new' => 'labo#create', as: "affiliations"

   #研究室パスワード移行ページ
    get  'labo_pass/:id' => 'labo_pass#index', as: "labo_pass"

  #実験結果ページ
    get  'experiment' => 'experiment#index'
    get  'experiment/show/:id' => 'experiment#show', as: "experiment_show"
    get  'experiment/new' => 'experiment#new', as: "new_experiment"
    post 'experiment/new' => 'experiment#create', as: "experiments"

  #コメント
    post 'experiment/show/:id' => 'experiment#comment_create', as: "comments"

  #研究室所属一覧


  get 'pages/show'
    get  'login' => 'login#index'
    get  'login/new'  =>  'login#new'
    get  'user' => 'user#index'
    get  'user/show/:id' => 'user#show', as: "user_show"

  #スタンダード(テンプレート)プロトコル一覧
    get  'standard' => 'standard#index'
    get  'standard/show/:id' => 'standard#show', as: "standard_show"
    get  'standard/new' => 'standard#new'

  #ベースプロトコル一覧
    get  'base' => 'base#index'
    get  'base/show/:id' => 'base#show', as: "base_show"
    get  'base/new' => 'base#new'

  #カスタムプロトコル一覧
    get  'custom' => 'custom#index'
    get  'custom/show/:id' => 'custom#show', as: "custom_show"
    get  'custom/new' => 'custom#new'


    get  'search' => 'search#index'


  end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    validates :university,  presence: true
    validates :department, presence: true
    validates :course,  presence: true
    validates :labo, presence: true
    validates :cord, presence: true, length: { minimum: 8 }
    has_many :users
    has_many :protocols
    has_many :experiments
end

app/models/category.rb
class Category < ApplicationRecord
    validates :category_name, presence: true
    has_many :experiments
    has_many :protocols
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :experiment
    validates :comment, presence: true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
    acts_as_taggable
    belongs_to :user
    belongs_to :protocol 
    belongs_to :category
    belongs_to :affiliation
    has_many :comments, dependent: :destroy
    attr_accessor :new_category
      
    validates :title, presence: true, length: { maximum: 20 } #仮で２０とした。不要かも
    validates :date, presence: true
    validates :overview, presence: true
    validates :result, presence: true
    validates :user_id, presence: true
    
    mount_uploader :image, ImageUploader
    
    #検索機能
    def self.search(keyword, user)
        return Experiment.where("affiliation_id = ?", user.affiliation_id) unless keyword
        Experiment.where('title LIKE ? AND affiliation_id = ?', "%#{keyword}%", user.affiliation_id).distinct
    end
    
    def self.search_admin(keyword)
        return Experiment.all unless keyword
        Experiment.where('title LIKE ?', "%#{keyword}%").distinct
    end
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :protocol

  validates :text, presence: true
  validates :position, presence: true
end

app/models/protocol.rb
class Protocol < ApplicationRecord
  belongs_to :user
  belongs_to :affiliation
  belongs_to :category
  has_many :procedures, inverse_of: :protocol, dependent: :destroy
  has_many :experiments
  has_many :comments

  attr_accessor :new_category

  acts_as_taggable

  accepts_nested_attributes_for :procedures, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
  validates :status, presence: true
  validates :parent_id, presence: true

  enum status: {base: 0, custom: 1, template: 2}

  # Constant for enum
  BASE = 0
  CUSTOM = 1
  TEMPLATE =2

  # add position to procedures
  after_save do |protocol|
    procedures = Procedure.where(protocol_id: protocol.id)
    add_position = 0
    procedures.each do |procedure|
      add_position += 1
      procedure.position = add_position
      procedure.save!
    end
  end
  
  #検索機能
  def self.search(keyword, num, user)
    return Protocol.where("status =? AND affiliation_id = ?", num, user.affiliation_id) unless keyword
    Protocol.where("status = ? AND affiliation_id = ? AND title LIKE ?", num, user.affiliation_id, "%#{keyword}%").distinct
  end
  
  def self.search_admin(keyword, num)
    return Protocol.where(status: num) unless keyword
    Protocol.where("status = ? AND title LIKE ?", num, "%#{keyword}%").distinct
  end
end

app/models/user.rb
class User < ApplicationRecord
  #include ActiveModel::Model
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

  belongs_to :affiliation
  has_many :experiments
  has_many :comments
  has_many :protocols

  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :avatar, AvatarUploader


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/custom_helper.rb
module CustomHelper
end

app/helpers/labo_helper.rb
module LaboHelper
    require 'securerandom'
end

app/helpers/labo_pass_helper.rb
module LaboPassHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
  def kind_of_protocol(status)
    if status == "template"
      return "テンプレートプロトコル"
    elsif status == "base"
      return "ベースプロトコル"
    elsif status == "custom"
      return "カスタムプロトコル"
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # 渡されたユーザーをログイン
  def log_in(user)
    session[:user_id] = user.id
  end

  # 永続セッションとしてユーザーを記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 記憶トークン (cookie) に対応するユーザーを返す
  def current_user
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/standard_helper.rb
module StandardHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(user)
    first_name = user.first_name
    last_name = user.last_name
    user_name = first_name + last_name
    return user_name
  end
end

app/views/admin/index.html.erb
<nav>

<%= render partial: "render/nav1" %>

</nav>

<main class="ADMIN-screen wf-roundedmplus1c">
  <article>
    <section id="BGP-researchable">
      <div class="BGP-Opacity1">
      <h1 class="R-TitleName2 text-center" style="margin-bottom: 75px;"><strong>管理画面トップ</strong></h1>
      <div class="container-fluid" style="max-width: 1200px;">        <!-- 全体を囲むコンテナ -->
        <div class="row justify-content-center">
          <div class="col-md-12 mt-4 mt-md-0">

            <div class="card-deck">

                  <div class="card icon">
                    <%= link_to new_affiliation_path, class: "icon-height275" do %>
                    <div class="card-body text-center">
                        <img class="icon-size" src="/assets/Admin/school.png">
                        <h5 class="icon-FontColor card-title text-center mt-4">新規研究室登録
                        </h5>
                    </div>
                    <% end %>
                  </div>

                  <div class="card icon">
                    <%= link_to '/labo', class: "icon-height275" do %>
                    <div class="card-body text-center">
                        <img class="icon-size" src="/assets/Admin/book.png">
                        <h5 class="icon-FontColor card-title text-center mt-4">登録研究室一覧
                      </h5>
                    </div>
                    <% end %>
                  </div>

                  <div class="card icon">
                    <%= link_to standard_new_path, class: "icon-height275" do %>
                    <div class="card-body text-center">
                        <img class="icon-size" src="/assets/Admin/flask.png">
                        <h5 class="icon-FontColor card-title text-center mt-4">新規テンプレート<br>プロトコル
                      </h5>
                    </div>
                    <% end %>
                  </div>

            </div>
          </div>
        </div>
      </div>                   <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>

app/views/render/_footer.html.erb
<footer>
  <div class="Blank" style="height: 75px; width: 100%; background: rgb(248, 249, 250); margin-top: 75px;">
  </div>
</footer>

app/views/render/_nav1.html.erb
  <nav class="navbar navbar-expand-md navbar-dark bg-light fixed-top primary-nav1 wf-roundedmplus1c" style="background-color: rgba(248, 249, 250, 0.57)!important">
    <a ><strong><%= link_to "Researchable", root_path, class: "navbar-brand", style: "color: black; font-size: 24px;" %></strong></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav1">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse primary-nav2" id="nav1">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'マイページ', edit_user_registration_path, class: "nav-link" %>
        </li>
        <%# if current_user.admin? %>
          <li class="nav-item active">
            <%= link_to '管理者ページ', admin_path, class: "nav-link" %>
          </li>
        <%# end %>
        <li class="nav-item active">
          <%= link_to '検索', search_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">研究室</a>
          <div class="dropdown-menu">
            <%= link_to '研究室ページ', root_path, class: "dropdown-item" %>
            <%= link_to '研究室一覧', '/labo', class: "dropdown-item" %>
            <%= link_to '研究室新規登録', '/labo/new', class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">新規投稿</a>
          <div class="dropdown-menu">
            <%= link_to 'テンプレートプロトコル', '/standard/new', class: "dropdown-item" %>
            <%= link_to 'ベースプロトコル', '/base/new', class: "dropdown-item" %>
          </div>
        </li>
         <li class="nav-item">
          <%= link_to 'ログアウト', destroy_session_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

app/views/render/_nav2.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-light fixed-top primary-nav1">
    <a href="#" class="navbar-brand nav-title">Researchable</a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav1">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse primary-nav2" id="nav1">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to '新規作成',  '/researchable' , style: 'text-decoration:none;' %></li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">メンバー</a>
          <div class="dropdown-menu">
            <a href="#" class="dropdown-item">山田太郎</a>
            <a href="#" class="dropdown-item">山田二郎</a>
            <a href="#" class="dropdown-item">山田三郎</a>
            <a href="#" class="dropdown-item">山田四郎</a>
          </div>
        </li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">メンバー</a>
            <ul class="dropdown-menu" style="width: 100%;">
              <li style="text-align: center; display: block; text-decoration: none;"><%= link_to '山田太郎', '/user' , style: 'text-decoration:none;'%></li>
              <li style="text-align: center; display: block;"><%= link_to '山田二郎', '/user', style: 'text-decoration:none;' %></li>
              <li style="text-align: center; display: block;"><%= link_to '山田三郎', '/user', style: 'text-decoration:none;' %></li>
              <li style="text-align: center; display: block;"><%= link_to '山田四郎', '/user', style: 'text-decoration:none;' %></li>
            </ul>
        </li>
        <li class="nav-item"><%= link_to '投稿',  '/researchable/new' , style: 'text-decoration:none;' %></li>
      </ul>
    </div>
  </nav>






  <nav class="navbar navbar-expand-md navbar-dark bg-light fixed-top primary-nav1 wf-roundedmplus1c" style="background-color: rgba(248, 249, 250, 0.57)!important">
    <a href="/admin" class="navbar-brand" style="color: black; font-size: 24px;"><strong>Researchable</strong></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav1">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse primary-nav2" id="nav1">
      <ul class="navbar-nav">
        <li class="nav-item active"><a href="/user/show" class="nav-link">マイページ</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">研究室</a>
          <div class="dropdown-menu">
            <li style="text-align: center; display: block;"><%= link_to '研究室ページ', '/user/show', style: 'text-decoration:none;' %></li>
            <a href="/labo/show" class="dropdown-item">研究室ページ</a>
            <a href="/labo" class="dropdown-item">研究室一覧</a>
            <a href="/labo/new" class="dropdown-item">研究室新規登録</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">新規投稿</a>
          <div class="dropdown-menu">
            <a href="/experiment/new" class="dropdown-item">実験結果</a>
            <a href="/standard/new" class="dropdown-item">テンプレートプロトコル</a>
            <a href="/custom/new" class="dropdown-item">ベースプロトコル</a>
            <a href="/experiment/new" class="dropdown-item">カスタムプロトコル</a>
          </div>
        </li>
         <li class="nav-item active"><a href="/users" class="nav-link">ログアウト</a></li>
      </ul>
    </div>
  </nav>

app/views/render/_nav3.html.erb
  <nav class="navbar navbar-expand-md navbar-dark bg-light fixed-top primary-nav1 wf-roundedmplus1c" style="background-color: rgba(248, 249, 250, 0.57)!important">
    <a href="/admin" class="navbar-brand" style="color: black; font-size: 24px;"><strong>Researchable</strong></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav1">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse primary-nav2" id="nav1">
      <ul class="navbar-nav">
        <li class="nav-item active"><a href="/user/show" class="nav-link">マイページ</a></li>
        <li class="nav-item active"><a href="/category" class="nav-link">カテゴリー</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">研究室</a>
          <div class="dropdown-menu">
            <%= link_to '研究室ページ', '/labo/show', class: "dropdown-item" %>
            <!-- <a href="/labo/show" class="dropdown-item">研究室ページ</a> -->
            <%= link_to '研究室一覧', '/labo' %>
            <!-- <a href="/labo" class="dropdown-item">研究室一覧</a> -->
            <%= link_to '研究室新規登録', '/labo/new' %>
            <!-- <a href="/labo/new" class="dropdown-item">研究室新規登録</a> -->
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown">新規投稿</a>
          <div class="dropdown-menu">
            <a href="/experiment/new" class="dropdown-item">実験結果</a>
            <a href="/standard/new" class="dropdown-item">テンプレートプロトコル</a>
            <a href="/base/new" class="dropdown-item">ベースプロトコル</a>
            <a href="/custom/new" class="dropdown-item">カスタムプロトコル</a>
          </div>
        </li>
         <li class="nav-item"><a href="/users" class="nav-link">ログアウト</a></li>
      </ul>
    </div>
  </nav>

app/views/render/tekito.html.erb
<main class="Login-screen">
  <article>
    <section id="BGP-researchable">
      <div class="BGP-Opacity5">
        <div class="container-fluid wf-roundedmplus1c">        <!-- 全体を囲むコンテナ -->
          <h1 class="R-TitleName text-center"><strong>Researchable</strong></h1>
          <h5 class="text-center" style="margin-bottom: 75px;">研究者の時間は、研究の為に・・・</h5>
          <div class="row justify-content-center">
            <div class="col-2"></div>
            <div class="col-10">
              <form>
                <div class="form-group form-row">
                  <label class="col-md-2 col-form-label text-md-left mb-4" for="Q_Name ">email</label>
                  <div class="col-md-6">
                    <input type="text" class="form-control" id="Q_Name">
                  </div>
                </div>
                <div class="form-group form-row mb-5">
                  <label class="col-md-2 col-form-label text-md-left" for="Q_Mail">パスワード</label>
                  <div class="col-md-6">
                    <input type="email" class="form-control" id="Q_Mail">
                  </div>
                </div>
                <div class="form-row">
                  <div class="col-9 text-center">
                    <button type="button" class="btn btn-outline-primary" style="margin-right: 10%;" onclick="location.href='/labo/show'">
                      <%= link_to "ログイン", class: 'btn btn-primary' %>
                    </button>
                    <%= link_to "新規登録画面", class: 'btn btn-outline-primary' %>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>                <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>




<!-- パスワード再発行ログインエラーの謎エラーコード（メールアドレスのレイアウトが崩れる） -->

<main class="Login-screen">
  <article>
    <section id="BGP-researchable">
      <div class="BGP-Opacity5">
        <div class="container-fluid wf-roundedmplus1c">        <!-- 全体を囲むコンテナ -->
          <h1 class="R-TitleName text-center"><strong>Researchable</strong></h1>
          <h5 class="text-center" style="margin-bottom: 75px;">研究者の時間は、研究の為に・・・</h5>
          <h2 class="text-center" style="margin-bottom: 75px;">パスワードの再発行</h2>
          <div class="row justify-content-center">
            <div class="col-2"></div>
            <div class="col-10">
              <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
              <%= devise_error_messages! %>
                <div class="form-group form-row">
                  <%= f.label :email, "メールアドレス", class: "col-md-2 col-form-label text-md-left mb-4" %><br />
                  <div class="col-md-6">
                    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
                  </div>
                </div>
                <div class="form-row">
                  <div class="col-9 text-center">
                    <%= f.submit "パスワードの再発行をする", class: "btn btn-outline-primary" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>                <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>

app/views/shared/_error_messages.html.erb
<% if @affiliation.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@affiliation.errors.count, "error") %>.
    </div>
    <ul>
    <% @affiliation.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>