config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations', shared: 'users/shared'}

  devise_scope :user do
    authenticated :user do
      root 'labo#show', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new'
    end
    get '/users/sign_out' => 'users/sessions#destroy', as: "destroy_session"
    get '/users/delete' => 'users/registrations#destroy', as: "destroy_registration"
    get 'users/labo' => 'users/registrations#retrieve_labo', as: 'retrieve_labo'
    post 'users/labo' => 'users/registrations#find_labo', as: "find_labo"
  end

  resources :protocols, only: [:index, :show, :new, :create, :destroy] do
    resources :procedures, only: [:create]
  end
  resources :custom_protocols, only: [ :new]


  #ログイン＆新規登録画面
    get  'thanks' => 'thanks#index'

     #管理画面トップ
    get  'admin' => 'admin#index'


   #研究室新規登録ページ&研究室ページ
    get  'labo' => 'labo#index'
    get  'labo/show/:id' => 'labo#show', as: "labo_show"
    get  'labo/new' => 'labo#new', as: "new_affiliation"
    post 'labo/new' => 'labo#create', as: "affiliations"

   #研究室パスワード移行ページ
    get  'labo_pass/:id' => 'labo_pass#index', as: "labo_pass"

  #実験結果ページ
    get  'experiment' => 'experiment#index'
    get  'experiment/show/:id' => 'experiment#show', as: "experiment_show"
    get  'experiment/new' => 'experiment#new', as: "new_experiment"
    post 'experiment/new' => 'experiment#create', as: "experiments"

  #コメント
    post 'experiment/show/:id' => 'experiment#comment_create', as: "comments"

  #研究室所属一覧


  get 'pages/show'
    get  'login' => 'login#index'
    get  'login/new'  =>  'login#new'
    get  'user' => 'user#index'
    get  'user/show/:id' => 'user#show', as: "user_show"

  #スタンダード(テンプレート)プロトコル一覧
    get  'standard' => 'standard#index'
    get  'standard/show/:id' => 'standard#show', as: "standard_show"
    get  'standard/new' => 'standard#new'

  #ベースプロトコル一覧
    get  'base' => 'base#index'
    get  'base/show/:id' => 'base#show', as: "base_show"
    get  'base/new' => 'base#new'

  #カスタムプロトコル一覧
    get  'custom' => 'custom#index'
    get  'custom/show/:id' => 'custom#show', as: "custom_show"
    get  'custom/new' => 'custom#new'


    get  'search' => 'search#index'


  end

app/models/user.rb
class User < ApplicationRecord
  #include ActiveModel::Model
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable#, :confirmable

  belongs_to :affiliation
  has_many :experiments
  has_many :comments
  has_many :protocols

  validates :first_name, presence: true
  validates :last_name, presence: true
  mount_uploader :avatar, AvatarUploader


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.admin
      @labo = Affiliation.find(params[:labo_id])
    else
      @labo = Affiliation.find(current_user.affiliation_id)
    end
    @users = User.where(affiliation_id: @labo.id).page(params[:page]).per(12)
  end


  def show
      @user = User.find(params[:id])
      @labo = Affiliation.find (@user.affiliation_id)
      @custom_protocols = Protocol.where(user_id: @user.id, status: 1).order(id: :asc).page(params[:page]).per(6)
      @experiments = Experiment.where(user_id: @user.id).order(id: :asc).page(params[:page]).per(6)
  end
  

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def retrieve_labo
  end
  
  def find_labo
    @labo = Affiliation.find_by(cord: params[:cord])
    if @labo
      flash[:notice] = '研究室が確認できました。'
      redirect_to new_user_registration_path(id: @labo.id)
    else
      flash[:alert] = "研究室が見つかりません"
      render "retrieve_labo"
    end
  end
  
  # GET /resource/sign_up
  def new
    @labo = Affiliation.find(params[:id])
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    @user = current_user
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    thanks_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    thanks_path
  end
  private

    
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
   super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(user)
    first_name = user.first_name
    last_name = user.last_name
    user_name = first_name + last_name
    return user_name
  end
end

app/views/user/index.html.erb
<nav>

<%= render partial: "render/nav1" %>

</nav>

<main class="MemberList-screen wf-roundedmplus1c">
  <article>
    <section id="BGP-researchable">
      <div class="BGP-Opacity1" style="padding-top: 100px;">
        <div class="container">
          <h1 class="R-TitleName3"><strong>~研究室：<%= @labo.labo %>~</strong></h1>
          <h2 class="my-5"><img class="icon-blank" src="/assets/Admin/member.png" style="">所属メンバー</h2>
        </div>
        <div class="container">        <!-- 全体を囲むコンテナ -->
          <div class="d-sm-flex flex-wrap text-black">
            <% @users.each do |user| %>
              <div class="bg-info p-3 mb-2 mr-sm-2 Member-Box">
                <%= link_to user_show_path(user), class: "A-Tag" do %>
                <div class="media A-TagEffect">
                  <%#= image_tag user.avatar.url, class: "Member-Avatar mr-3" %>
                  <div class="media-body" style="">
                    <h4><%= "Adimn: " if user.admin %><%= user.last_name + " " + user.first_name %></h4>
                  </div>
                </div>
                <% end %>
              </div>
            <% end %>
            <%= paginate @users %>
          </div>
        </div>        <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>

app/views/user/show.html.erb
<nav>

<%= render partial: "render/nav1" %>

</nav>


<main class="Users-screen wf-roundedmplus1c">
  <article>
    <section id="BGP-researchable">
      <div class="BGP-Opacity1">
      <div class="container" style="margin-bottom: 75px;">        <!-- 全体を囲むコンテナ -->
        <h1 class="R-TitleName3" style="margin-bottom: 50px;"><strong>~<%= @labo.labo %>~</strong></h1>
        <div class="d-sm-flex flex-wrap text-black">
          <div class="bg-info p-3 mb-2 mr-sm-2 Member-Box">
            <div class="media A-TagEffect">
              <%#= image_tag @user.avatar.url, class: "Member-Avatar mr-3" %>
              <div class="media-body" style="">
                <h4><%= @user.last_name + " " + @user.first_name %></h4>
                <% if @user.eql? current_user %>
                  <%= link_to "プロフィールの編集", edit_user_registration_path(resource) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
<div class="container">        <!-- 全体を囲むコンテナ -->
  <h2 class="my-5"><img class="icon-blank" src="/assets/Admin/file.png">カスタムプロトコル</h2>

  <div class="d-sm-flex flex-wrap text-black ">
    <% @custom_protocols.each do |custom| %>
      <div class="bg-info p-3 mb-2 mr-sm-2 Custom-Box">
        <%= link_to custom_show_path(custom), class: "A-Tag" do %>
          <div class="A-TagEffect">
            <h5>プロトコル名：<%= custom.title %></h5>
            <p class="mb-0">作成日時：<%= custom.created_at %></p>
            <p class="mb-0">カテゴリー名：＊後ほど追加予定＊</p> 
          </div>
        <% end %>
      </div>
    <% end %>
    <%= paginate @custom_protocols %>
  </div>

</div>        <!-- 全体を囲むコンテナ -->

<div class="container">        <!-- 全体を囲むコンテナ -->
  <h2 class="my-5"><img class="icon-blank" src="/assets/Admin/result.png">実験結果</h2>

  <div class="d-sm-flex flex-wrap text-black">
  <% @experiments.each do |experiment| %>
    <div class="bg-info p-3 mb-2 mr-sm-2 Result-Box">
      <%= link_to experiment_show_path(experiment), class: "A-Tag" do %>
        <div class="A-TagEffect">
          <h5><%= experiment.title %></h5>
          <p class="mb-0">作成日時：<%= experiment.date %></p>
          <p class="mb-0">カテゴリー名：<%= experiment.category.category_name %></p>
        </div>
      <% end %>
    </div>
  <% end %>
  <%= paginate @experiments %>
  </div>

</div>        <!-- 全体を囲むコンテナ -->
      </div>
    </section>
  </article>
</main>